"""Совместимая обёртка над пакетом ``runtime`` (бывший god-файл).

Исторически весь движок проверки узлов жил в этом файле (~5000 строк).
Миграция завершена: единственная реализация — пакет ``runtime/``:

  runtime.types           — константы и dataclass-ы;
  runtime.uritools        — канонизация URI / дедупликация;
  runtime.parse           — парсинг ссылок и тел подписок;
  runtime.fetch           — загрузка подписок (happ:// расшифровка, зеркала);
  runtime.netsocks        — SOCKS5-клиент и HTTP(S) поверх SOCKS;
  runtime.probes_ping     — дешёвые TCP/UDP-пинги;
  runtime.probes_telegram — MTProto-латентность + медиа-фильтр t.me/s/;
  runtime.probes_speed    — замеры скорости (NDT7, Cloudflare, OVH, Tele2);
  runtime.configs         — сборка конфигов xray/sing-box;
  runtime.procs           — управление процессами ядер (Job Objects);
  runtime.core            — XrayCoreRuntime + collect_subscription_nodes;
  runtime.singbox_pool    — пакетная проверка через sing-box;
  runtime.happ_decrypt    — расшифровка happ://cryptN/ (Hiddify).

Этот модуль сохраняет старые пути импорта
``from xray_runtime import ...`` — весь код проекта продолжает работать
без изменений. Новый код должен импортировать из ``runtime`` напрямую.
"""
from __future__ import annotations

from runtime.types import (
    BLOCKED_MEDIA_TARGETS,
    CHATGPT_PROBE_TARGETS,
    GSTATIC_GENERATE_204,
    INSTAGRAM_PROBE_TARGETS,
    IP_SB_IP,
    M_LAB_LOCATE_URL,
    M_LAB_NDT7_SAMPLE_SEC,
    M_LAB_NDT7_TIMEOUT_SEC,
    NODE_LINK_RE,
    PING_HTTPS_TARGETS,
    SING_BOX_PROTOCOLS,
    SUBSCRIPTION_USER_AGENT,
    TELEGRAM_API_HEAD_TARGET,
    TELEGRAM_DCS,
    TELEGRAM_MEDIA_DC,
    TELEGRAM_PROBE_TARGETS,
    TELEGRAM_XRAY_PROBE_TOTAL,
    TG_MEDIA_MIN_BODY_BYTES,
    TG_MEDIA_MIN_KBPS,
    TG_MEDIA_PAGE_HOST,
    TG_MEDIA_PAGE_PATH,
    TG_MEDIA_RANGE_SPAN,
    TG_MEDIA_VIDEO_SRC_RE,
    TG_MEDIA_VIDEO_TAG_RE,
    TG_MEDIA_WINDOW_BYTES,
    XRAY_ACTIVE_SPEED_TEST_BYTES,
    XRAY_ACTIVE_SPEED_TEST_SECONDS,
    XRAY_DEAD_SOURCE_COOLDOWN_SEC,
    XRAY_DEAD_SOURCE_FAILURES,
    XRAY_GOOD_DOWNLOAD_KBPS,
    XRAY_MIN_MEDIA_KBPS,
    XRAY_PROBE_SPEED_TEST_BYTES,
    XRAY_PROBE_SPEED_TEST_SECONDS,
    XRAY_PROTOCOLS,
    XRAY_SPEED_TEST_HOST,
    XRAY_SPEED_TEST_PATH,
    XRAY_SPEED_UPLOAD_PATH,
    XrayNode,
    XrayProbeResult,
    XrayRuntimeConfig,
    _LOYAAL_FINGERPRINTS,
    _SAFE_DEFAULT_FINGERPRINT,
    _safe_fingerprint,
    _truthy,
)

from runtime.uritools import (
    NODE_SCHEMES,
    _BASE64_QUERY_PARAMS,
    _decode_base64,
    _decode_base64_plain,
    _node_dedup_text,
    _normalize_base64_padding,
    _normalize_ss_userinfo,
    _sanitize_node_uri,
)

from runtime.parse import (
    DEFAULT_XRAY_SUBSCRIPTIONS,
    LEGACY_XRAY_SUBSCRIPTION_PATTERNS,
    _candidate_score,
    _clash_query,
    _decode_base64_multi,
    _looks_like_readable_text,
    _node_lines_from_candidate,
    _node_link_from_clash_proxy,
    _node_link_from_json_object,
    _node_links_from_clash_yaml,
    _node_links_from_json,
    _node_links_from_text,
    _parse_shadowsocks,
    _parse_uri_node,
    _parse_vmess,
    _query_from_json_transport,
    _shadowsocks_link_from_json,
    _split_host_port,
    _standard_link_from_json,
    _subscription_lines,
    is_legacy_xray_subscription,
    parse_node_link,
)

from runtime.fetch import (
    _decode_subscription_body,
    _fetch_text,
    _subscription_candidate_urls,
    _subscription_headers,
    _subscription_ssl_contexts,
    _subscription_timeouts,
)

from runtime.netsocks import (
    _recv_exact,
    _socks_https_download_kbps,
    _socks_https_get_body,
    _socks_https_head_status,
    _socks_https_latency,
    _socks_https_upload_kbps,
    _socks_open_connection,
)

from runtime.probes_ping import (
    UDP_PROTOCOLS,
    _tcp_ping_node,
    _tcp_udp_ping_node,
    _udp_ping_node,
)

from runtime.probes_telegram import (
    _encode_abridged_packet,
    _read_abridged_packet,
    _socks_mtproto_latency,
    _tg_media_probe,
    _tg_media_ranged_download,
    _tg_media_video_urls,
)

from runtime.probes_speed import (
    XRAY_SPEED_TEST_BIG_BYTES,
    XRAY_SPEED_TEST_BIG_SECONDS,
    _download_speed_probe,
    _mlab_cache_until,
    _mlab_cached_url,
    _mlab_fetch_target,
    _mlab_ndt7_download_kbps,
    _ws_build_frame,
    _ws_read_frame,
    _ws_url_to_target,
    _xray_download_speed,
    _xray_upload_speed,
)

from runtime.configs import (
    SingBoxUnsupported,
    _normalize_reality_pbk,
    _resolve_stream_fingerprint,
    _sing_box_config,
    _sing_box_outbound,
    _sing_box_supports,
    _sing_box_tls,
    _sing_box_transport,
    _write_temp_config,
    _xray_config,
    _xray_outbound,
    _xray_stream_settings,
)

from runtime.procs import (
    _assign_process_to_job,
    _cleanup_stale_bundle_cores,
    _close_windows_handle,
    _create_kill_on_close_job,
    _find_free_port,
    _pid_exists,
    _resolve_binary,
    _subprocess_no_window,
    _terminate_pid_tree,
    _terminate_process_tree,
    _windows_terminate_pid_tree,
    _windows_terminate_process,
)

from runtime.core import (
    SING_BOX_UTLS_FINGERPRINTS,
    XRAY_SUBSCRIPTION_FETCH_WORKERS,
    XrayCoreRuntime,
    _FORCED_RUNTIME,
    _collect_from_source,
    _normalize_core_mode,
    _normalize_selection_strategy,
    _reason_counts,
    _reason_summary,
    _resolved_core_mode,
    _result_from_row,
    _wait_if_paused,
    _xray_result_sort_key,
    collect_subscription_nodes,
    get_default_core_mode,
    get_forced_runtime,
    set_default_core_mode,
    set_forced_runtime,
)

__all__ = [
    'BLOCKED_MEDIA_TARGETS',
    'CHATGPT_PROBE_TARGETS',
    'DEFAULT_XRAY_SUBSCRIPTIONS',
    'GSTATIC_GENERATE_204',
    'INSTAGRAM_PROBE_TARGETS',
    'IP_SB_IP',
    'LEGACY_XRAY_SUBSCRIPTION_PATTERNS',
    'M_LAB_LOCATE_URL',
    'M_LAB_NDT7_SAMPLE_SEC',
    'M_LAB_NDT7_TIMEOUT_SEC',
    'NODE_LINK_RE',
    'NODE_SCHEMES',
    'PING_HTTPS_TARGETS',
    'SING_BOX_PROTOCOLS',
    'SING_BOX_UTLS_FINGERPRINTS',
    'SUBSCRIPTION_USER_AGENT',
    'SingBoxUnsupported',
    'TELEGRAM_API_HEAD_TARGET',
    'TELEGRAM_DCS',
    'TELEGRAM_MEDIA_DC',
    'TELEGRAM_PROBE_TARGETS',
    'TELEGRAM_XRAY_PROBE_TOTAL',
    'TG_MEDIA_MIN_BODY_BYTES',
    'TG_MEDIA_MIN_KBPS',
    'TG_MEDIA_PAGE_HOST',
    'TG_MEDIA_PAGE_PATH',
    'TG_MEDIA_RANGE_SPAN',
    'TG_MEDIA_VIDEO_SRC_RE',
    'TG_MEDIA_VIDEO_TAG_RE',
    'TG_MEDIA_WINDOW_BYTES',
    'UDP_PROTOCOLS',
    'XRAY_ACTIVE_SPEED_TEST_BYTES',
    'XRAY_ACTIVE_SPEED_TEST_SECONDS',
    'XRAY_DEAD_SOURCE_COOLDOWN_SEC',
    'XRAY_DEAD_SOURCE_FAILURES',
    'XRAY_GOOD_DOWNLOAD_KBPS',
    'XRAY_MIN_MEDIA_KBPS',
    'XRAY_PROBE_SPEED_TEST_BYTES',
    'XRAY_PROBE_SPEED_TEST_SECONDS',
    'XRAY_PROTOCOLS',
    'XRAY_SPEED_TEST_BIG_BYTES',
    'XRAY_SPEED_TEST_BIG_SECONDS',
    'XRAY_SPEED_TEST_HOST',
    'XRAY_SPEED_TEST_PATH',
    'XRAY_SPEED_UPLOAD_PATH',
    'XRAY_SUBSCRIPTION_FETCH_WORKERS',
    'XrayCoreRuntime',
    'XrayNode',
    'XrayProbeResult',
    'XrayRuntimeConfig',
    '_BASE64_QUERY_PARAMS',
    '_FORCED_RUNTIME',
    '_LOYAAL_FINGERPRINTS',
    '_SAFE_DEFAULT_FINGERPRINT',
    '_assign_process_to_job',
    '_candidate_score',
    '_clash_query',
    '_cleanup_stale_bundle_cores',
    '_close_windows_handle',
    '_collect_from_source',
    '_create_kill_on_close_job',
    '_decode_base64',
    '_decode_base64_multi',
    '_decode_base64_plain',
    '_decode_subscription_body',
    '_download_speed_probe',
    '_encode_abridged_packet',
    '_fetch_text',
    '_find_free_port',
    '_looks_like_readable_text',
    '_mlab_cache_until',
    '_mlab_cached_url',
    '_mlab_fetch_target',
    '_mlab_ndt7_download_kbps',
    '_node_dedup_text',
    '_node_lines_from_candidate',
    '_node_link_from_clash_proxy',
    '_node_link_from_json_object',
    '_node_links_from_clash_yaml',
    '_node_links_from_json',
    '_node_links_from_text',
    '_normalize_base64_padding',
    '_normalize_core_mode',
    '_normalize_reality_pbk',
    '_normalize_selection_strategy',
    '_normalize_ss_userinfo',
    '_parse_shadowsocks',
    '_parse_uri_node',
    '_parse_vmess',
    '_pid_exists',
    '_query_from_json_transport',
    '_read_abridged_packet',
    '_reason_counts',
    '_reason_summary',
    '_recv_exact',
    '_resolve_binary',
    '_resolve_stream_fingerprint',
    '_resolved_core_mode',
    '_result_from_row',
    '_safe_fingerprint',
    '_sanitize_node_uri',
    '_shadowsocks_link_from_json',
    '_sing_box_config',
    '_sing_box_outbound',
    '_sing_box_supports',
    '_sing_box_tls',
    '_sing_box_transport',
    '_socks_https_download_kbps',
    '_socks_https_get_body',
    '_socks_https_head_status',
    '_socks_https_latency',
    '_socks_https_upload_kbps',
    '_socks_mtproto_latency',
    '_socks_open_connection',
    '_split_host_port',
    '_standard_link_from_json',
    '_subprocess_no_window',
    '_subscription_candidate_urls',
    '_subscription_headers',
    '_subscription_lines',
    '_subscription_ssl_contexts',
    '_subscription_timeouts',
    '_tcp_ping_node',
    '_tcp_udp_ping_node',
    '_terminate_pid_tree',
    '_terminate_process_tree',
    '_tg_media_probe',
    '_tg_media_ranged_download',
    '_tg_media_video_urls',
    '_truthy',
    '_udp_ping_node',
    '_wait_if_paused',
    '_windows_terminate_pid_tree',
    '_windows_terminate_process',
    '_write_temp_config',
    '_ws_build_frame',
    '_ws_read_frame',
    '_ws_url_to_target',
    '_xray_config',
    '_xray_download_speed',
    '_xray_outbound',
    '_xray_result_sort_key',
    '_xray_stream_settings',
    '_xray_upload_speed',
    'collect_subscription_nodes',
    'get_default_core_mode',
    'get_forced_runtime',
    'is_legacy_xray_subscription',
    'parse_node_link',
    'set_default_core_mode',
    'set_forced_runtime',
]
